---
name: "CUPS"
version: "dev"
slug: "cups-airprint"
description: "A CUPS print server with working AirPrint"
url: "https://github.com/joschi/homeassistant-addons"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
usb: true
init: false
homeassistant_api: true
host_network: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
ingress: true
ingress_port: 0
panel_icon: mdi:printer
map:
  - config:rw
